### ISSUE TITLE
Pending refactors and removals

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#21]
This is a list of directories and files that do not make sense or are of the wrong format/style.

This will be updated in future.

Refactors
------
- `VoxelisedXCAT/` -> `VoxelisedSimulation/`?

- Directories to CamelCase format.

Removals
-----

- `VoxelisedXCAT/activity.h33` and `VoxelisedXCAT/attenuation.h33` are unnessisery now.

**Comment by KrisThielemans** [comment]
`VoxelisedSimulation` sounds good to me

**Comment by robbietuk** [comment]
> `VoxelisedSimulation` sounds good to me

PR incoming with additional changes

**Comment by robbietuk** [comment]
Fixed by #22
