### ISSUE TITLE
Suggestion: Populate a common template .hroot from STIR sinogram template header and GATE scanner geometry

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#27]
The information present in the hroots are duplicates of those present in the STIR scanner template and GATE scanner geometry.

```
originating system
Number of rings
Number of detectors per ring
Inner ring diameter (cm)
Average depth of interaction (cm) 
Distance between rings (cm)    
Default bin size (cm)                   
View offset (degrees)       
Maximum number of non-arc-corrected bins
```

Information such as `number of Rsectors`, `number of modules_X`, `number of submodules_X`, `number of crystals_X`, etc. are all present in the GATE scanner geometry.

These fields can easily be populated using sed commands.

**Comment by KrisThielemans** [comment]
I wouldn't go there. Far better to add something to STIR that creates the macros and hroot. see #6

**Comment by robbietuk** [comment]
I guess it is almost the same thing but using predefined macros. I agree that #6 would cover this
