### ISSUE TITLE
Suggestion: for the "ExampleSTIR-GATE.sh"

### ISSUE THREAD

**Issue by GeorgeSoult** [UCL/STIR-GATE-Connection#32]
Hi,

In the line 60, I suggest the script to be instead of:
./SetupSimulation.sh $ScannerType $StoreRootFilesDirectory $Activity $Attenuation
to become:
./SetupSimulation.sh $ScannerType $StoreRootFilesDirectory **$ActivityFilename** **$AttenuationFilename**

Given that few lines previously, we declared the file names. 
Also, I have a question. about executing .sh. When I run it with "./" it gives me errors with the if statements. I have to change everything to "bash" to run it properly (i.e.: bash SetupSimulation.sh $ScannerType $StoreRootFilesDirectory $ActivityFilename $AttenuationFilename).

Regards,

George

**Comment by robbietuk** [comment]
Hi, thanks for the input.

You are correct. https://github.com/UCL/STIR-GATE-Connection/blob/8f499f1716c5a2ee437f452a5cc98326e041eb04/VoxelisedSimulation/ExampleSTIR-GATE.sh#L60
can be 
`./SetupSimulation.sh $ScannerType $StoreRootFilesDirectory $ActivityFilename $AttenuationFilename`. In the current implementation the script is generating the same image twice, which is a mistake. If you wouldnt mind doing a PR for that change, that would be useful :)

With regard to the to the if statement, I assume that it is failing on https://github.com/UCL/STIR-GATE-Connection/blob/8f499f1716c5a2ee437f452a5cc98326e041eb04/VoxelisedSimulation/SetupSimulation.sh#L48  but it could be 
https://github.com/UCL/STIR-GATE-Connection/blob/8f499f1716c5a2ee437f452a5cc98326e041eb04/VoxelisedSimulation/SetupSimulation.sh#L39-L40
could you please confirm and maybe provide a copy of the terminal output? 

Robbie
