### ISSUE TITLE
Suggestion: Fix file structure to make more sense

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#38]
Currently the file structure does not make too much sense. Everything is currently run from `STIR-GATE-Connection/VoxelisedSimulation/` and the main scripts are there. The project "Home" directory contains `ExampleScanners/`, `ExamplePhantoms/` and `VoxelisedSimulation/`.

I propose that the content of `VoxelisedSimulation/` be moved into the main directory, which would continue to contain `ExampleScanners/` and `ExamplePhantoms/` .

Currently no rush for this. It would break a lot of backwards compatibility. Maybe aim for v2.0?

**Comment by KrisThielemans** [comment]
I don't know. I don't mind a clean project directory with very little in there...

Possibly the name `VoxelisedSimulation` doesn't quite cover it anymore.

I'd consider more moving remain scripts in `images` elsewhere. It's very nonintuitive that they are there.

I'd also consider moving https://github.com/UCL/STIR-GATE-Connection/blob/master/VoxelisedSimulation/Output/Templates/lm_to_projdata_template.par elsewhere, which would then happily allow you to get rid of `Output` (Obviously you'd have to create those directories then in the script, but at some point you want to allow the output to be in other places, so then you'd have to create them anyway)

I wouldn't worry about backwards compatibility just yet. You haven't release v1.0 yet anyway 😄 . About time that you do though.

**Comment by robbietuk** [comment]
>I don't know. I don't mind a clean project directory with very little in there...
Possibly the name VoxelisedSimulation doesn't quite cover it anymore.

Prehaps you're right, the name of the directory bugs me... and the fact `ExamplePhantoms/` and `ExampleScanners/` are in there. I will move them.

The templates and additional scripts will also be moved so `Output/` doesn't contain anything. See #37

**Comment by robbietuk** [comment]
This was partly addressed by #41

**Comment by robbietuk** [comment]
My above comment was incorrect. This is all addressed by #41 except for the renamed of `VoxelisedSimulation/`, which is fine for now. Closing.
