### ISSUE TITLE
stir_math unable to read .hdr outputs from GATE simulatuions

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#40]
`stir_math` is unable to read the `.hdr`/`.img` outputs of GATE

`VoxelisedSimulation/images/output/CreateActivity.sh` https://github.com/UCL/STIR-GATE-Connection/blob/master/VoxelisedSimulation/images/output/CreateActivity.sh 
and `VoxelisedSimulation/images/output/CreateAttenuation.sh` https://github.com/UCL/STIR-GATE-Connection/blob/master/VoxelisedSimulation/images/output/CreateAttenuation.sh
were written to convert the true source and used GATE attenuation into interfile format. 

However I get error
```
stir_math attenuation.hv Phantomtest-MuMap.hdr

Available input file formats:
Interfile

ERROR: no file format found that can read file 'Phantomtest-MuMap.hdr'
libc++abi.dylib: terminating with uncaught exception of type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
zsh: abort      stir_math attenuation.hv Phantomtest-MuMap.hdr
```
where `Phantomtest-MuMap.hdr` exists and is an output from a `test` GATE simulation but is a binary file, content:
```
5c01 0000 6473 7200 0100 0000 0101 2f68
6f6d 6500 0100 0000 30ab 3617 d37f 0000
0000 0000 0000 7230 0400 6e00 6e00 4000
0100 0000 0000 0000 6d6d 000c 4271 2f63
6300 a01a 0100 1000 0000 0000 0000 0000
0000 8040 0000 8040 0000 8240 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 803f 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 ff7f 0000
0000 0000 696d 6167 6500 12e4 fe7f 0000
d6f9 e30b 0100 0000 6038 12e4 fe7f 0000
0000 0000 0000 0000 a040 5117 3800 0000
0100 0000 0031 0000 3800 0000 0000 0000
3800 0000 0000 0000 0039 12e4 3800 0000
0100 0000 6e6f 6e65 0000 0000 2100 0000
0000 0000 0000 0000 6008 5317 306e 6f6e
6500 5117 d37f 006e 6f6e 6500 0000 0000
306e 6f6e 6500 0000 0039 126e 6f6e 6500
a7f8 6714 016e 6f6e 6500 0000 0000 f06e
6f6e 6500 0000 0000 006e 6f00 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 
```

I have added this issue to this project as I believe it is a GATE issue, not STIR.

**Comment by robbietuk** [comment]
Files are readable by AMIDE

**Comment by KrisThielemans** [comment]
I haven't checked where these come from, but traditionally `.hdr`/`.img` pairs are in Analyze format. STIR can read that via ITK. So, you need to have ITK installed when you build STIR (and set the CMake variable `ITK_DIR` if it didn't find it).

**Comment by robbietuk** [comment]
That will be the problem, I dont use ITK. I guess this is another dependancy for the project.

**Comment by KrisThielemans** [comment]
yes. it's possible that you could convince GATE to output in another file format, but life is short... Easiest to tell people to build STIR with ITK.

On most systems this shouldn't be hard. you can have a look at `STIR/.travis.yml` for Mac instructions for instance. The STIR conda build does come with ITK support. And there's the SIRF-SuperBuild that will build ITK  for you if you want to, and then build STIR (and SIRF) ok.
