### ISSUE TITLE
GATE output voxelised images are reflected in z

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#48]
This is somewhat related to #47, but slightly different and therefore a seperate issue.

The `Phantom-SourceMap` and `Phantom-MuMap` output by GATE are reflected in the z axis compared to the input. This first figure is the first slice for the input `attenuation_corrected.hv` and output `Phantom-MuMap.hdr`
![image](https://user-images.githubusercontent.com/13292409/89887093-a1558c80-dbc5-11ea-988f-40bdbfca751a.png)

This second figure is the central slice of each (of 24/47) indicating now reflection in x or y
![image](https://user-images.githubusercontent.com/13292409/89887248-d95ccf80-dbc5-11ea-95cb-e09c7764926e.png)

@francescaleek Have you noticed any of this in your experiments?

**Comment by robbietuk** [comment]
The same thing is present for the emission/source maps.

**Comment by KrisThielemans** [comment]
ah well. also with `mhd`? @danieldeidda introduced `invert_axis` for this kind of problem

**Comment by francescaleek** [comment]
I haven't done enough work with STIR-GATE to have seen this behaviour. The only time I have had to correct for this kind of thing before was when working with e7 tools. I'll look out for it in GATE, glad to hear there's already a fix!

**Comment by robbietuk** [comment]
> ah well. also with `mhd`? @danieldeidda introduced `invert_axis` for this kind of problem

Unfortunately yes.

`invert_axis` worked perfectly.

I have questioned the GATE list to see if this is expected behaviour.

**Comment by robbietuk** [comment]
I never recieved a response from the GATE list. I have no clue what might cause this behaviour. I have added the ability to `invert_axis` to the scatter estimation script, which is currently the only script that uses the attenuation image (for use in the compuation of the `acf`), see #50.

I guess this will also be a problem when trying to extract ROI information from the source distributions.

**Comment by robbietuk** [comment]
Resolved by #71
