### ISSUE TITLE
estimation of normalisation factors will fail for D690

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR-GATE-Connection#59]
Found by @francescaleek. Discussion is at https://github.com/UCL/STIR/issues/838 and https://github.com/UCL/STIR/issues/837.

This needs to be resolved at the STIR level.

**Comment by robbietuk** [comment]
For the record, the `offset=-8` is correct for the D690, or best guess based upon the difference between the unlisted GATE simulation of a 3 point source phantom and the STIR forward projection. Difference between sinograms of unlisted GATE data and STIR forward projection with `offset=-8`. Blue (negitive) is GATE data and red (positive) is STIR forward projection
![image](https://user-images.githubusercontent.com/13292409/109802863-39759a80-7c18-11eb-90cb-ef3af009ea8a.png)

This is not to say the ML norm code will work as that is a subtly different issue relating to blocks and buckets.

**Comment by KrisThielemans** [comment]
indeed. the offset is there to get the rotations sorted for the projections, but it messes up the ML norm sadly (which I hadn't thought about...)

**Comment by francescaleek** [comment]
Results from GATE sim of D690FOVCylinder, unlisted with offset set to -8 in the first instance, then 0; bucket efficiency factors calculated taking only geometric factors into account.

`offset (num of detectors) := -8`
![image](https://user-images.githubusercontent.com/56024383/109873422-9f3c4380-7c65-11eb-86a3-9da1dc0cc7a9.png)
![image](https://user-images.githubusercontent.com/56024383/109873499-bb3fe500-7c65-11eb-81c0-34b7e102a2c7.png)
`offset (num of detectors) := 0`
![image](https://user-images.githubusercontent.com/56024383/109873889-4de08400-7c66-11eb-82ae-3e9d9d4c6e3e.png)
![image](https://user-images.githubusercontent.com/56024383/109874935-acf2c880-7c67-11eb-9a6e-37694c0069e4.png)

Strangely, I get a warning
`WARNING: CListModeDataROOT: I've set the scanner from STIR settings and ignored values in the hroot header.`
but it did pick up the change...

**Comment by KrisThielemans** [comment]
alright! that worked.

> Strangely, I get a warning
> `WARNING: CListModeDataROOT: I've set the scanner from STIR settings and ignored values in the hroot header.`
> but it did pick up the change...

as you probably didn't change the `.hroot` aside from the `offset`, I guess you had this before. Or you changed the template but not the `hroot` (as you cannot).

Question is now how to move forward with this, aside from fixing STIR... That'll be for tomorrow!

**Comment by KrisThielemans** [comment]
can you also show GATE/eff/model. should be quite flat

**Comment by francescaleek** [comment]
It is:
![image](https://user-images.githubusercontent.com/56024383/109880306-a9af0b00-7c6e-11eb-9d70-1ffc19c695e6.png)

**Comment by KrisThielemans** [comment]
excellent! can you enable the eff_iter now? It shouldn't change anything really.

**Comment by francescaleek** [comment]
Yes, overall change is small. Some effects are assigned to crystal efficiency, resulting in a lower overall efficiency.
![image](https://user-images.githubusercontent.com/56024383/109935230-47352980-7cc5-11eb-820a-033a6e294837.png)
![image](https://user-images.githubusercontent.com/56024383/109935319-5f0cad80-7cc5-11eb-967b-e989fedf4e71.png)
![image](https://user-images.githubusercontent.com/56024383/109935500-92e7d300-7cc5-11eb-882a-81e0a7cdd7fe.png)
![image](https://user-images.githubusercontent.com/56024383/109938029-764c9a80-7cc7-11eb-90ae-695f353206fa.png)

**Comment by KrisThielemans** [comment]
thanks for checking. would you mind showing the quotient of the total efficiency factors for both cases (as opposed to the difference, as they are multiplicative factors) ?

**Comment by francescaleek** [comment]
Oops, of course...
![image](https://user-images.githubusercontent.com/56024383/109945530-41444600-7ccf-11eb-8f98-ec8636919942.png)

**Comment by KrisThielemans** [comment]
ok. wrong title for the picture I guess.

The overall bias surprises me. Hard to understand that... The rest is likely just noise. (There are more crystal efficiencies to estimate, so therefore the result is noisier).

**Comment by robbietuk** [comment]
A temporary D690 sinogram header that will allow of the `normalisation`/`eff_factors` to be compted as per above:

```
!INTERFILE  :=
!imaging modality := PT
name of data file := D690FOV_f1g1d0b0.s
!version of keys := STIR4.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 47
matrix axis label [3] := view
!matrix size [3] := 288
matrix axis label [2] := axial coordinate
!matrix size [2] := { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 381
minimum ring difference per segment := { -23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23}
maximum ring difference per segment := { -23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23}
Scanner parameters:= 
Number of rings                          := 24
Number of detectors per ring             := 576
Inner ring diameter (cm)                 := 81.02
Average depth of interaction (cm)        := 0.94
Distance between rings (cm)              := 0.654
Default bin size (cm)                    := 0.21306
View offset (degrees)                    := -5.021
Maximum number of non-arc-corrected bins := 381
Default number of arc-corrected bins     := 331
Energy resolution := 0.124
Reference energy (in keV) := 511
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 6
Number of crystals per block in transaxial direction        := 18
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
end scanner parameters:=
effective central bin size (cm) := 0.226074
number of time frames := 1
number of energy windows := 1
energy window lower level[1] := 425
energy window upper level[1] :=  650
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
```
_N.B._ This does not work on unlisting due to scanner checks in the STIR unlisting code. Therefore this temporary modification must be made after the GATE data is unlisted.

**Comment by robbietuk** [comment]
Back projection of unlisted GATE simulation of a `ThreePointActivity` phantom with various `View offset (degrees)` values. _N.B._ `offset (num of detectors) := 0` in the `hroot`.
 
`View offset (degrees) := 0 `. Observed clockwise rotation.
![image](https://user-images.githubusercontent.com/13292409/111133782-cef71f80-8572-11eb-92f0-a2aea934ffbe.png)
`View offset (degrees) := -5.021`. Observed minimal rotation
![image](https://user-images.githubusercontent.com/13292409/111133905-f5b55600-8572-11eb-85f1-e7a0545746be.png)
`View offset (degrees) := +5.021`. Observed significantly clockwise roation.
![image](https://user-images.githubusercontent.com/13292409/111133940-fea62780-8572-11eb-852d-c5d3c8b80120.png)

**Comment by KrisThielemans** [comment]
I guess a fused image with the ground truth could have helped, but I take it that you say that -5.021 fits very well?

Please also check forward projections of the ground truth, ideally also in a very oblique segment.

**Comment by robbietuk** [comment]
Image based rotation check
--------
![image](https://user-images.githubusercontent.com/13292409/111151682-b34a4400-8587-11eb-867b-f1a780f863f8.png)
See the single blue dots from the true image in the center of each backprojected region. Images have been rescaled.

> [...]but I take it that you say that -5.021 fits very well?

Yes, the two offset voxels with value should be offset in only x and y from the central voxel, generated using https://github.com/UCL/STIR-GATE-Connection/blob/master/ExamplePhantoms/STIRparFiles/ThreePointActivity.par


Projections
-----
Low segment number:
![image](https://user-images.githubusercontent.com/13292409/111149693-1a1a2e00-8585-11eb-81d6-ab59e1c6367c.png)

Oblique segment:
![image](https://user-images.githubusercontent.com/13292409/111150167-a9bfdc80-8585-11eb-8b92-f71e17af6e75.png)

(Sinogram values have been rescaled)

**Comment by KrisThielemans** [comment]
Looks pretty good to me!

**Comment by robbietuk** [comment]
Note to other users. Until ML norm code in STIR is fixed to handle buckets instead of only block (https://github.com/UCL/STIR/issues/838) we cannot compute the norm using the standard D690 header. 

However, the work around for the normalisation computation still exist: https://github.com/UCL/STIR-GATE-Connection/issues/59#issuecomment-797445057
The norm can be computed using this modified D690 header and then re-subsitute the standard D690 header file.

**Comment by robbietuk** [comment]
I do believe that the randoms estimation (from delayed events) uses the same code as the normalisation sinogram computation.

https://github.com/UCL/STIR-GATE-Connection/blob/ea4a62cd2d90ccf89d4b3d2ae2d119792d0b69ab/VoxelisedSimulation/SubScripts/EstimateRandomsFromDelayed.sh#L36-L43

**Comment by robbietuk** [comment]
There is a subtle difference between using the modified and "standard" SITR scanners, probably due to noise. Nothing to worry about IMO:

Difference:
![ModRandoms-Randoms](https://user-images.githubusercontent.com/13292409/111435527-cfb9be00-86f8-11eb-8b53-67d9202d12d6.png)

Quotient:
![modRandoms_div_Randoms](https://user-images.githubusercontent.com/13292409/111435536-d2b4ae80-86f8-11eb-80d5-19631f64108c.png)

**Comment by KrisThielemans** [comment]
The randoms estimation uses the "crystal efficiency" part of the ML norm code only. (randoms-rate = 2tau singles-rate singles-rate).     It should not care about blocks and buckets, or indeed view offset. If it does, that'd be rather weird.

**Comment by robbietuk** [comment]
Everything looks good. I was concerned it may use some of the symmetries, but it appears it doesnt.

**Comment by KrisThielemans** [comment]
but results should be identical...

**Comment by robbietuk** [comment]
The output of:
https://github.com/UCL/STIR-GATE-Connection/blob/ea4a62cd2d90ccf89d4b3d2ae2d119792d0b69ab/VoxelisedSimulation/SubScripts/EstimateRandomsFromDelayed.sh#L36-L38
is
```
${factors}_geo_1.out
${factors}_block_1.out
${factors}_eff_1_1.out
${factors}_eff_1_2.out
...
${factors}_eff_1_10.out
```
There is no `diff` between eff factors for the default and modified D690.

However, even though it specifies `num_iterations=0` the geo and block infomation is created. Removing the geo and block files before  `apply_normfactors3D $OutputFilename $factors ones.hs 1 1 $eff_iters` is computed results in an error. These files are different between the default and modified D690, snipets below. 

Default D690: [randoms_factors_block_1.txt](https://github.com/UCL/STIR-GATE-Connection/files/6155896/randoms_factors_block_1.txt)

Modified D690: [randoms_factors_mod_block_1.txt](https://github.com/UCL/STIR-GATE-Connection/files/6155897/randoms_factors_mod_block_1.txt)

**Comment by robbietuk** [comment]
I am unsure as the the current status of this issue or whether it is still an issue...

**Comment by robbietuk** [comment]
Closing because I feel we fixed most of the issues here with STIR changes and rotations
