### ISSUE TITLE
the unit of reconstructed image

### ISSUE THREAD

**Issue by mele-y** [UCL/STIR-GATE-Connection#91]
Hello,I‘m using the mMR macro file from this repository and successfully reconstructed the image from root file. Is the unit of the image reconstructed using STIR Bq/ml or other units?

**Comment by robbietuk** [comment]
The reconstructed image will not be of any standard units by default. The units will correspond to some activity intensity but correction is needed for standardisation. I am not well read in that literature but check around some of the GATE simulation papers, this should be a fairly common methodology.

**Comment by KrisThielemans** [comment]
STIR recons at the moment are proportional to counts (note that we don't do dead-time modelling).
Some related info is given in https://github.com/UCL/STIR/issues/571

**Comment by mele-y** [comment]
ok,appreciate your help
